# Generated by Django 4.2 on 2023-05-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('num_telephone', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cv/')),
                ('experience', models.TextField()),
                ('lettre_motivation', models.TextField()),
            ],
        ),
    ]
